project:
  name: 'UrbanNav_Citywalk'
  run_name: 'toy_data_pretrain'
  result_dir: 'results'

training:
  batch_size: 8
  max_epochs: 10
  gpus: 1
  amp: true
  normalize_step_length: true
  resume: true
  direction_loss_weight: 1.0
  reg_coeff: 0.1

scheduler:
  name: 'cosine'
  step_size: 10
  gamma: 0.1

optimizer:
  name: 'adamw'
  lr: 1e-4

model:
  do_rgb_normalize: true
  do_resize: true
  obs_encoder:
    type: 'resnet50'
    context_size: 5
    target_size: 5
  encoder_feat_dim: 1024
  ema_range: [0.998, 1]
  decoder:
    type: 'attention'
    len_traj_pred: 5
    num_heads: 8
    num_layers: 16
    ff_dim_factor: 4

data:
  type: citywalk
  video_dir: '/home/xinhao/citywalk/test_videos'
  num_workers: 3
  pose_fps: 5
  video_fps: 30
  target_fps: 1
  num_train: 40
  num_val: 20
  num_test: 20

logging:
  enable_wandb: false  # Set to false to disable Wandb logging
  pbar_rate: 1