project:
  name: 'UrbanNav_Citywalk'
  run_name: 'toy_data'
  result_dir: 'results'

training:
  batch_size: 8
  max_epochs: 10
  gpus: 1
  amp: false

scheduler:
  name: 'cosine'
  step_size: 10
  gamma: 0.1

optimizer:
  name: 'adamw'
  lr: 5e-4

model:
  do_transform: true
  obs_encoder:
    type: 'efficientnet-b0'
    context_size: 5

  cord_embedding:
    type: 'polar'
    num_freqs: 6
    include_input: true

  encoder_feat_dim: 512

  decoder:
    type: 'attention'
    len_traj_pred: 5
    num_heads: 2
    num_layers: 2
    ff_dim_factor: 4

data:
  type: citywalk
  video_dir: '/home/xinhao/citywalk/test_videos'
  pose_dir: '/mnt/DATA/citywalk/test_output/saved_trajectories'
  num_workers: 3
  pose_fps: 5
  video_fps: 30
  target_fps: 1
  num_train: 60
  num_val: 20
  num_test: 20
  input_noise: 0.01 # sigma in meter
  search_window: 50 
  arrived_threshold: 5 

testing:
  num_visualize: 10

logging:
  enable_wandb: true  # Set to false to disable Wandb logging