project:
  name: 'UrbanNav_Citywalk'
  run_name: 'toy_data'
  result_dir: 'results'

training:
  batch_size: 6
  max_epochs: 10
  gpus: 1
  amp: true
  normalize_step_length: true
  resume: false
  direction_loss_weight: 5.0
  distance_loss_weight: 1.0
  angle_loss_weight: 1.0

scheduler:
  name: 'cosine'
  step_size: 10
  gamma: 0.1

optimizer:
  name: 'adamw'
  lr: 1e-5

model:
  do_rgb_normalize: true
  do_resize: true
  obs_encoder:
    type: 'dinov2_vitb14'
    context_size: 5
    crop: [350, 630]
    resize: [350, 630]
    freeze: true
  output_coordinate_repr: 'euclidean'

  cord_embedding:
    type: 'target'
    num_freqs: 6
    include_input: true

  encoder_feat_dim: 768

  decoder:
    type: 'diff_policy'
    len_traj_pred: 5
    num_heads: 4
    num_layers: 4
    ff_dim_factor: 4
    num_diffusion_iters: 10

data:
  type: citywalk
  video_dir: '/home/xinhao/citywalk/test_videos'
  pose_dir: '/mnt/DATA/citywalk/test_output/saved_trajectories'
  num_workers: 4
  pose_fps: 5
  video_fps: 30
  target_fps: 1
  num_train: 40
  num_val: 20
  num_test: 2
  input_noise: 0.1 # sigma (after normalization)
  search_window: 50 # frames
  arrived_threshold: 5 # num frame
  arrived_prob: 0.3

validation:
  num_visualize: 100
testing:
  num_visualize: 100

logging:
  enable_wandb: false  # Set to false to disable Wandb logging
  pbar_rate: 1