project:
  name: 'UrbanNav_robodog'
  run_name: 'robodog'
  result_dir: 'results'

training:
  batch_size: 6
  max_epochs: 10
  gpus: 1
  amp: false
  normalize_step_length: flase
  resume: true

scheduler:
  name: 'cosine'
  step_size: 10
  gamma: 0.1

optimizer:
  name: 'adamw'
  lr: 1e-4

model:
  do_rgb_normalize: true
  do_resize: true
  obs_encoder:
    type: 'efficientnet-b0'
    context_size: 5

  cord_embedding:
    type: 'polar'
    num_freqs: 6
    include_input: true

  encoder_feat_dim: 512

  decoder:
    type: 'attention'
    len_traj_pred: 5
    num_heads: 2
    num_layers: 2
    ff_dim_factor: 4

data:
  type: urbannav
  image_root_dir: '/mnt/HDD1/jl17001/dog_data'
  pose_dir: '/mnt/HDD1/jl17001/dog_data/match_gps_pose'
  num_workers: 15
  pose_fps: 5
  video_fps: 30
  target_fps: 1
  num_train: 1
  num_val: 1
  num_test: 1
  input_noise: 0.1 # sigma (after normalization)
  search_window: 50 # frames
  arrived_threshold: 5 # meters
  arrived_prob: 0.3

validation:
  num_visualize: 100
testing:
  num_visualize: 100

logging:
  enable_wandb: false  # Set to false to disable Wandb logging
  pbar_rate: 1